version: '2'

services:
  provider_a:
    build:
      context: .
      dockerfile: ./docker/provider/Dockerfile
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8001
      - SLEEP_TIME=1
      - SOURCE_FILE=./response_a.json
    ports:
      - 8001:8001
    volumes:
      - ./provider/:/code

  provider_b:
    build:
      context: .
      dockerfile: ./docker/provider/Dockerfile
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8002
      - SLEEP_TIME=20
      - SOURCE_FILE=./response_b.json
    ports:
      - 8002:8002
    volumes:
      - ./provider/:/code

  redis:
    image: redis:5.0.5
    ports:
      - 6379:6379

  