# Generated by Django 3.1 on 2022-11-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
